### ISSUE TITLE
En tant que membre, lorsque je consulte une plante, depuis l'onglet "Découvrir, je peux cliquer sur les catégories listées 

### ISSUE THREAD

**Issue by gaetan-pc** [floriscope/floriscope-mobile#101]
## Comportement attendu

- Lorsqu'un membre consulte le détail d'une plante, et qu'il a activé l'onglet "Découvrir", il peut cliquer sur l'une des entrées de la liste
- L'utilisateur est alors diriger vers un nouvel écran
- Cet écran liste l'ensemble des collections associées à la plante et filtrées par la catégorie sélectionnée
- Le header de cet écran rappelle l'intitulé de la catégorie sélectionnée
- Un bouton de retour est présent dans ce header
- Chaque entrée de la liste, affiche le nom de la collection, son image et le nombre de plantes présentes dans la liste. 

## Écrans concernés

> PlantScreen - Écran principal de consultation d'une plante

> PlantCollectionsScreen - Ecran secondaire de consultation des collections associées à une plante

## Navigation

| Ordre     | Type d'écran                         |
| --------- | ------------------------------------ |
| Précédent | Détail d'une plante|
| Suivant   | Détail d'une collection |

## Ressource(s )API

|Endpoint      | Params          | Documentation         |
| ---------- | ------------- | --------------------- |
| [GET] {baseUrl}/v1/plantes/{plante_id}/collections| `category`, `page`, `per_page`| *in progress* (alternative, see Paw Cloud Project)|

## Maquette(s) écran

| ![IMG_20181112_130220.jpg](https://images.zenhubusercontent.com/5a6b0ac14b5806bc2bc46635/eceeb0d7-dc8b-46f7-951a-91adb4feb0d5)|
| :-------: |
| Screen Mockup |

**Comment by loiclouvet** [comment]
Dans l'écran, nous avions ajouté un champ de recherche. Il n'est pas cité dans le "Comportement attendu". On l'implémente ?
