### ISSUE TITLE
En tant que membre, lorsque je consulte le détail d'une plante, je peux voir un bandeau picto+valeurs détaillant ses principales caractéristiques

### ISSUE THREAD

**Issue by gaetan-pc** [floriscope/floriscope-mobile#105]
## Navigation

| Ordre     | Type d'écran                         |
| --------- | ------------------------------------ |
| Précédent | ... |
| Suivant   | ...                                  |

**Comment by gaetan-pc** [comment]
@loiclouvet afin de permettre l'affichage de ce bandeau, je pense ajouter un attribut supplémentaire `icons` dans la réponse renvoyée par un `GET {base_url}/v1/plantes/:plante_id`. Le format prévu est le suivant: 

```javascript
{
  plante: {
    ...,
    icons: [
      {key: "category" , image: "https://images.com/azerty.jpg", caption: "conifères"},
      {key: "flower-colors", image: "https://images.com/qsdfg.jpg", caption: "rose, blanc" }
    ]
  }
}
```
Je travaille dessus actuellement.

**Comment by gaetan-pc** [comment]
## Critères à afficher

  -[  ] Catégorie
  -[  ] Hauteur
  -[  ] Couleur des fleurs

**Comment by gaetan-pc** [comment]
@loiclouvet non c'est juste les critères qu'on compte illustrer dans un premier temps

**Comment by gaetan-pc** [comment]
@loiclouvet voici l'url test demandé: `http://assets.floriscope.io/mobile/images/plante-icons/category@1x.png`
J'essaie de mettre en place le certificat SSL

**Comment by gaetan-pc** [comment]
@loiclouvet il me semble que le filtre de la précédente version (0.3.1) n'a pas été désactivé dans la version en cours (0.3.2).
Les images des pictos ne s'affichent pas sur iOS. Penses-tu que ce soit lié au fait qu'elles soient transmises via http au lieu de https?

**Comment by loiclouvet** [comment]
@gaetan-pc j'ai omis d'enlever le filtre. Concernant les images, je vais regarder si le mapping est bon.
