### ISSUE TITLE
En tant que membre, je peux modifier les informations de mon compte

### ISSUE THREAD

**Issue by gaetan-pc** [floriscope/floriscope-mobile#135]
## Comportement(s) attendu(s)
 
 - [ ] Modification de la **photo de profil** : en cliquant sur l'icône de l'image, en menu bas s'affiche avec la possibilité de prendre un photo ou de sélectionner une photo disponible dans la galerie de l'appareil
 - [ ] Modification du **nom unique d'utilisateur** `username`
 - [ ] Modification de l'**adresse électronique** `email`
 - [ ] Modification de la **catégorie de profil** `category`
 - [ ] Modification du nom de l'entreprise / structure `organization`
 - [ ] Mise à jour de la description du profil
 - [ ] Possibilite de **supprimer le compte** , demande de confirmation de la suppression via fenêtre de type alerte, avec le texte: 

>"Cette action est définitive. Êtes-vous sûr de vouloir supprimer votre compte Floriscope? Oui(en rouge) / Non (en bleu) "

## Navigation

| Ordre     | Type d'écran                         |
| --------- | ------------------------------------ |
| Précédent | Écran principal d'édition des paramètres |
| Suivant   | :no_mobile_phones:                                  |

## Ressource(s )API

| Type          | Description                          |
| ------------- | ------------------------------------ |
| REST Endpoint | `[PUT/PATCH]{base_url}/v1/users/me` avec le header `Authorization` défini avec token JWT valide  |
| Documentation | voir Paw, `User/Update User` , en particulier la structure du corps de la requête                                |

## Maquette(s) écran

| ![image.png](https://images.zenhubusercontent.com/5a6b0ac14b5806bc2bc46635/d821f57c-6a16-45be-b1d9-2945d6dfd998) |
| :-------: |
| SettingsAccountScreen |

**Comment by loiclouvet** [comment]
> REST Endpoint | <ressource_api_baseurl>/auth/sign_in

Après le signup, j'ai utilisé `v1/users/me`, n'est-ce pas plutôt cet endpoint ?
Comment modifier l'image du profil ? Quels sont les paramètres que je dois modifier pour chaque input ?

**Comment by gaetan-pc** [comment]
>Après le signup, j'ai utilisé v1/users/me, n'est-ce pas plutôt cet endpoint ?

@loiclouvet je viens de modifier la description du ticket. Les paramètres à modifier sont listé dans l'exemple Paw

**Comment by loiclouvet** [comment]
Vu avec toi @gaetan-pc, utiliser `/v1/users/me`
