### ISSUE TITLE
En tant que membre, je peux modifier mon mot de passe 

### ISSUE THREAD

**Issue by gaetan-pc** [floriscope/floriscope-mobile#136]
## Comportement(s) attendus
- [ ] Depuis le menu principal d'éditions des paramètres du compte, lorsque je clique sur le lien ** Sécurité ** l'utilisateur connecté est redirigé vers un écran d'édition de son mot de passe.
- [ ] Pour définir un nouveau mot de passe, l'utilisateur connecté doit rapeller son mot de passe actuel.
- [ ] Il peut ensuite saisir son nouveau mot de passe puis confirmer la modification en cliquant sur le boutton **Valider**
- [ ] pour les 2 inputs de mot de passe il sera possible d'afficher les mots de passe en cours de saisie en cliquant sur une icône :eye: situé à droit des 2 inputs
- [ ] l'utilisateur peut abandonner la modification de son mot de passe en cliquant sur le bouton de retour situé en dans la barre de menu haut
## Navigation

| Ordre     | Type d'écran                         |
| --------- | ------------------------------------ |
| Précédent | Écran de menu d'édition des paramètres du compte |
| Suivant   | :no_mobile_phones:                                  |

## Ressource(s )API

| Type          | Description                          |
| ------------- | ------------------------------------ |
| REST Endpoint | [PATCH] {base_url}/v1/users/me/change_password  |
| Documentation | voir Paw `User/Change current password`                                  |

## Maquette(s) écran

|  ![image.png](https://images.zenhubusercontent.com/5a6b0ac14b5806bc2bc46635/cae59371-fdc8-4cce-a08e-9f4d91172954)  |
| :-------: |
| SettingsSecurityScreen |

**Comment by loiclouvet** [comment]
Design implémenté. Je me base également sur le tableau 'inputs' du retour endpoint lors d'une erreur pour afficher les erreurs. @gaetan-pc

**Comment by gaetan-pc** [comment]
>Sur Paw, je vois un endpoint PUT: /users/password, est-ce celui la ? @gaetan-pc

Désolé! je viens de mettre à jour l'issue. Le *endpoint* à utiliser est `PATCH: /v1/users/me/change_password`
