### ISSUE TITLE
En tant que membre, je peux partager mon avis ou des suggestions

### ISSUE THREAD

**Issue by gaetan-pc** [floriscope/floriscope-mobile#139]
## Comportement(s) attendu(s)
- [ ] lorsque l'utilisateur connecté clique sur le lien **Discussions**, il est dirigé vers un écran lui permettant de partager sur son avis ou des suggestions
- [ ] ...

## Navigation

| Ordre     | Type d'écran |
| --------- | --------------- |
| Précédent | ...                     |
| Suivant   | :no_mobile_phones:                       |

## Ressource(s )API

| Type          | Description                          |
| ------------- | ------------------------------------ |
| REST Endpoint | `[POST]{base_url}/v1/feedbacks` |
| Documentation | voir exemple Paw, `Feedback/Post a feedback`  |
| Notes | `review` est le texte de l'avis/suggestion (obligatoire), `mood` est l'humeur de l'utilisateur peut seulement être `['angry', 'neutral', 'happy']` et `logs` est un objet à schéma libre permettant de rmonter des informations complémentaires utile (OS, device, durée de session...) |

## Maquette(s) écran

|  ![image.png](https://images.zenhubusercontent.com/5a6b0ac14b5806bc2bc46635/d688da18-b338-4ac8-9367-1fbb66acc327)image_1  |
| :-------: |
| caption_1 |

**Comment by loiclouvet** [comment]
Je comprends pas très bien le terme "Discussions", il s'agit ici d'un écran de contact, non ?

**Comment by loiclouvet** [comment]
En attente d'info concernant l'endpoint API

**Comment by gaetan-pc** [comment]
>En attente d'info concernant l'endpoint API

En construction, certainement disponible en fin de journée lundi prochain car je serais en réunion toute la matinée...

**Comment by gaetan-pc** [comment]
@loiclouvet oui elle est disponible. Voir dans description mise à jour de l'issue
