### ISSUE TITLE
Changer l'URL de l'image dans les résultats de recherche de plantes

### ISSUE THREAD

**Issue by gaetan-pc** [floriscope/floriscope-mobile#152]
De nouvelles versions des images sont disponibles dans l'index Algolia.
Plus d'infos ici: https://github.com/gaetan-pc/vegebase-api/pull/84
Utiliser `image_mobile.hit_card_3x`

**Comment by loiclouvet** [comment]
Je n'ai pas accès au lien @gaetan-pc.
