### ISSUE TITLE
Suivi des actions utilisateurs

### ISSUE THREAD

**Issue by gaetan-pc** [floriscope/floriscope-mobile#17]

**Comment by loiclouvet** [comment]
Paquet: https://github.com/idehub/react-native-google-analytics-bridge
Pré-requis: tracker Id + accès au compte Analytics.

TODO:
- [ ] Tracking des écrans
- [ ] Tracking des "Touch" sur les éléments "touchables"

@gaetan-pc Peux-tu confirmer cette todo list s'il te plait ?

**Comment by gaetan-pc** [comment]
@loiclouvet je te partagerais un dossier de travail avec un ensemble de variables d'environnement (dont le trackerId de GA) + accès aux comptes de service tiers si nécessaire.
