### ISSUE TITLE
En tant que membre, je peux créer/éditer une liste de plante

### ISSUE THREAD

**Issue by gaetan-pc** [floriscope/floriscope-mobile#172]
## Comportement(s) attendus

Un utilisateur connecté peut créer une nouvelle liste de plantes depuis:
* l'écran d'association d'une plante à une liste
* l'onglet "Mes listes" la page de profil utilisateur

Le formulaire de création d'une liste de plantes permettra de définir:

*  **[requis]** le titre de la liste:`title`
* **[requis]** la catégorie de la liste: `category` à choisir parmi `["Catalogue","Disponible en production","Patrimoine arboré","Collection botanique","Liste thématique","Projet d'aménagement paysager","Aménagement paysager","Victoire du paysage","Apprentissage et reconnaissance"]` 
* l'image de couverture de la liste: `image` codée en base64
* le statut de publication de la liste: `is_published` par défaut _false_ (liste privée)
* la localisation/adresse de la liste: `address`
* un page web associée à cette liste: `external_link`
* une emphase, information importante à publier: `disclaimer`
* la description sommaire de la liste: `lead`
* la description complète de la liste: `description`

En mode édition, si des plantes sont déjà associées à cette listes, l'utilisateur peut accéder à une page de gestion des specimens

## Navigation

| Ordre     | Type d'écran                         |
| --------- | ------------------------------------ |
| Précédent | Ecran d'ajout d'une à une liste / Ecran de profil Utilisateur (onglet mes listes) |
| Suivant   | ...                                  |

## Ressource(s )API

| Type          | Description                          |
| ------------- | ------------------------------------ |
|Création | [POST]<ressource_api_baseurl>/users/me/collections |
| Édition | [PUT]<ressource_api_baseurl>/users/me/collections/:collection_id |

## Maquette(s) écran

| ![image](https://user-images.githubusercontent.com/3033273/51688816-aa880400-1ff5-11e9-86ac-a7735738055f.png)|
| :-------: |
| maquette formulaire de création/édition |

**Comment by loiclouvet** [comment]
@gaetan-pc Je ne vois pas de possibilité de modifier/ajouter le `disclaimer`.

Coté API, il semblerait qu'il soit impossible d'envoyer  un `external_link` ?
En cas d'erreur, le format de la réponse ne me revoit pas les `inputs` qui ne sont pas corrects.

**Comment by loiclouvet** [comment]
@gaetan-pc 
Actuellement, erreur 500 sur l'API d'edition d'une collection: `https://api.vegebase.net/v1/collections/21`

**Comment by loiclouvet** [comment]
> En mode édition, si des plantes sont déjà associées à cette listes, l'utilisateur peut accéder à une page de gestion des specimens
Suite réunion du 27/02, à enlever.

**Comment by gaetan-pc** [comment]
> @gaetan-pc Je ne vois pas de possibilité de modifier/ajouter le `disclaimer`.
> Coté API, il semblerait qu'il soit impossible d'envoyer un `external_link` ?

Parmi les modifications faites sur l'API de gestion des collections, j'avais oublié l'ajout des ces nouveaux attributs. C'est maintenant corrigé.

**Comment by gaetan-pc** [comment]
> En cas d'erreur, le format de la réponse ne me revoit pas les `inputs` qui ne sont pas corrects.

@loiclouvet Ce que je n'arrive pas à valider pour l'instant c'est le format base64 pour les images. J'ai essayé de placer des validations sur le modèle mais ça ne fonctionne pas. Je vais essayer de les placer au niveau du contrôleur. 
Également, à réaliser l'envoi d'erreurs si le schéma transmis via la requête ne correspond pas au schéma  de données autorisé.
Pour le reste, les erreurs ont le format de réponse suivant:
```javascript
{
  "errors": {
    "messages": [
      "Title doit être rempli(e)",
      "Category a reçu une valeur non autorisée. Choisir une valeur parmi: [\"Catalogue\", \"Disponible en production\", \"Patrimoine arboré\", \"Collection botanique\", \"Liste thématique\", \"Projet d'aménagement paysager\", \"Aménagement paysager\", \"Victoire du paysage\", \"Apprentissage et reconnaissance\"]",
      "Latitude doit être supérieur ou égal à -90",
      "Longitude n'est pas un nombre",
      "Tags doit être un tableau de valeurs (array) et contenir au moins une valeur",
      "External link n'est pas une URL valide"
    ],
    "inputs": [
      "title",
      "category",
      "latitude",
      "longitude",
      "tags",
      "external_link"
    ],
    "details": {
      "title": [
        "doit être rempli(e)"
      ],
      "category": [
        "a reçu une valeur non autorisée. Choisir une valeur parmi: [\"Catalogue\", \"Disponible en production\", \"Patrimoine arboré\", \"Collection botanique\", \"Liste thématique\", \"Projet d'aménagement paysager\", \"Aménagement paysager\", \"Victoire du paysage\", \"Apprentissage et reconnaissance\"]"
      ],
      "latitude": [
        "doit être supérieur ou égal à -90"
      ],
      "longitude": [
        "n'est pas un nombre"
      ],
      "tags": [
        "doit être un tableau de valeurs (array) et contenir au moins une valeur"
      ],
      "external_link": [
        "n'est pas une URL valide"
      ]
    }
  },
  "response": {
    "code": 422
  }
}
```

**Comment by gaetan-pc** [comment]
![image](https://user-images.githubusercontent.com/3033273/54322950-72fe0700-45f7-11e9-90a7-82002199a6e0.png)
