### ISSUE TITLE
En tant que membre, depuis la page de détails d'une collection, je peux ajouter des plantes à cette collection si j'en suis le propriétaire

### ISSUE THREAD

**Issue by gaetan-pc** [floriscope/floriscope-mobile#174]
## Comportement(s) attendus

* Depuis l'écran de consultation des spécimens d'une liste, l'utilisateur peut en ajouter de nouvelles via le bouton "Ajouter une plante"; Ce bouton est affiché seulement si l'utilisateur connecté est le propriétaire de la liste.
* Ce bouton renvoie vers un formulaire dont le comportement attendu est le suivant:
  * le premier input renvoie vers un écran de sélection de plante qui comprend une barre de recherche (comportement similaire à l'écran de recherche des plantes); lorsque l'utilisateur touche un résultat de recherche, la plante est sélectionné-> l'attribut `plante_id` est ajouté dans l'objet à renvoyer vers le serveur -> l'utilisateur retourne sur le formulaire -> le nom scientifique (`taxon`) est ajouté à l'input
   * le second input est une carte centrée (par ordre de disponibilité de l'information) (1)sur la position actuelle de l'utilisateur, (2) la position de la collection , (3) centre de la France métropolitaine si aucune des données précédente disponible. Lorsque l'utilisateur touche la carte, les attributs `latitude` et `longitude` sont ajouté au body de la requête
  * le troisième input est un champ texte simple qui renvoie vers l'attribut `description` à ajouter au body de la requête

## Navigation

| Ordre     | Type d'écran                         |
| --------- | ------------------------------------ |
| Précédent | Ecran de consultation de la liste des plantes associées à la collection (specimens) |
| Suivant   | ...                                  |

## Ressource(s )API

| Type          | Description                          |
| ------------- | ------------------------------------ |
| REST Endpoint | [POST] <api_base_url>/v1/collections/:id/specimens |
| Documentation | ...                                  |

## Maquette(s) écran

|  ![image](https://user-images.githubusercontent.com/3033273/51751327-e59d3c80-20b4-11e9-8a19-a01f99d85ee3.png) |
| :-------: |
| **Modification de l'écran de consultation des specimens** |

|  ![image](https://user-images.githubusercontent.com/3033273/51751366-fe0d5700-20b4-11e9-8e2d-9c85b41056c0.png) |
| :-------: |
| **Formulaire d'ajout d'un specimen** |

| ![image](https://user-images.githubusercontent.com/3033273/51751409-1aa98f00-20b5-11e9-9838-3fd939f4795f.png)|
| :-------: |
| **Ecran de sélection d'une plante** |

**Comment by loiclouvet** [comment]
@gaetan-pc L'API `[POST] <api_base_url>/v1/collections/:id/specimens` renvoie actuellement une erreur 500. Peux-tu regarder ?

**Comment by gaetan-pc** [comment]
@loiclouvet 

> L'API [POST] <api_base_url>/v1/collections/:id/specimens renvoie actuellement une erreur 500. Peux-tu regarder ?
Normalement fonctionne de nouveau. À tester (je viens de mettre à jour Paw pour le détail sur le body et le contenu des réponses succès et erreurs)

**Comment by gaetan-pc** [comment]
### Demandes d'évolutions (au 15/04/19)  

- [x] `L’API [POST] <api_base_url>/v1/collections/:id/specimens renvoie actuellement une erreur 500` -> de nouveau opérationnel
  - voir sur Paw 
- [x] API pour l’édition ? ->
  - **[PUT] <api_base_url>/v1/collections/:collection_id/specimens/:id** voit Paw pour plus de détails sur le format du corps de la requête et du format de la répose
- [x] Map: search bar 
  - avec mapbox ? **OUI** voir https://docs.mapbox.com/api/search/
  - Combien de résultats affichés ? **5**
- [ ] Markers -> _…wip_
- [ ] Default zoom/coordinates -> ...wip
