### ISSUE TITLE
En tant que membre, depuis la page de détails d'une collection, je peux gérer la liste des spécimens associés à cette collection si j'en suis le propriétaire

### ISSUE THREAD

**Issue by gaetan-pc** [floriscope/floriscope-mobile#181]
## Comportement(s) attendus

* Depuis la page de consultation des specimens d'une collection, je peux passer cette liste en mode édition si je suis le propriétaire de la liste.
* En mode édition, les specimens ne sont plus regroupés selon l'attribut `plante_id`: les doublons de plantes apparaissent clairement.
* En mode édition, des *checkboxes* apparaissent devant les cartes des spécimens.
* Si au moins un specimen est sélectionné, un icône de suppression (type poubelle) apparaît.
* Si l'utilisateur clique sur cette icône, une fenêtre de confirmation de la suppression apparaît.
* En mode édition, une icône type crayon apparaît sur chaque carte.
* Au toucher sur ces cartes, l'utilisateur navigue vers une page d'édition des specimens voir #174
                                |

## Ressource(s )API

| Type          | Description                          |
| ------------- | ------------------------------------ |
| Suppression des spécimens | [DELETE] <baseUrl>/v1/specimens/:specimen_id |
| Édition des spécimens | [PUT] <baseUrl>/v1/specimens/:specimen_id                                  |

## Maquette(s) écran

|  ![image.png](https://images.zenhubusercontent.com/5a6b0ac14b5806bc2bc46635/63f5d74a-be5d-4e44-8484-ec5d25fa8809) |
| :-------: |
| **Écran des specimens d'une collection (mode édition)** |

**Comment by loiclouvet** [comment]
![Uploading ManageListV2@2x.png…](nouveau design)

**Comment by loiclouvet** [comment]
@gaetan-pc Existe-t-il une API pour supprimer l'ensemble des spécimens d'une même espèce ?

**Comment by loiclouvet** [comment]
@gaetan-pc 
> [DELETE] /v1/specimens/:specimen_id

avec un bon `specimen_id` renvoie une erreur 404.

**Comment by gaetan-pc** [comment]
- [x] `API delete semble KO` -> de nouveau opérationnel 
  - [DELETE] /v1/specimens/:_id
  - [DELETE] v1/collections/:collection_id/specimens/:id
- [x] `Existe-t-il une API pour supprimer l’ensemble des spécimens d’une même espèce ?` -> maintenant oui
  - **[DELETE] /v1/collections/:collection_id/specimens/destroy_all** pour supprimer tous les specimens d'une collection
  - **[DELETE] /v1/collections/:collection_id/specimens/destroy_all?plante_id=456** pour supprimer toutes les specimens d'une collection appartenant à une espèce donnée

**Comment by gaetan-pc** [comment]
@loiclouvet évolutions/améliorations API à tester

**Comment by loiclouvet** [comment]
> @loiclouvet évolutions/améliorations API à tester

J'utilise uniquement les API `[DELETE] /v1/collections/:collection_id/specimens/destroy_all?plante_id=XX` et `[DELETE] /v1/specimens/:_id`.
Les tests sont 🆗 !
