### ISSUE TITLE
En tant que membre, depuis l'écran de consultation des specimens d'une collection, je peux afficher cette liste en mode carte

### ISSUE THREAD

**Issue by gaetan-pc** [floriscope/floriscope-mobile#182]
## Comportement(s) attendus

* Si le nouvel attribut `is_mappable` d'une collection est `true`, une icône permettant de consulter une carte des specimens est ajouté à l'écran de consultation des specimens.
* Si l'utilisateur touche cet icône, il navigue vers une carte de l'ensemble des spécimens géolocalisés pour cette collection.
* Un carrousel situé en bas de l'écran permet d'afficher les informations du spécimen sélectionné.
* Un marqueur (map-marker) différent est utilisé pour distinguer le specimen sélectionné et affiché en bas de la carte (dans le carrousel).

## Ressource(s )API

| Type          | Description                          |
| ------------- | ------------------------------------ |
| Récupération des specimens géolocalisés | [GET] <baseUrl>/v1/collections/:collection_id/specimens?is_geolocated=true |
| Documentation | ...                                  |

## Maquette(s) écran

|  ![image.png](https://images.zenhubusercontent.com/5a6b0ac14b5806bc2bc46635/c623dde6-2a26-41ae-b299-ddcdef151624)  |
| :-------: |
| **Écran de consultation des specimens (mode Carte)** |

**Comment by loiclouvet** [comment]
Que se passe-t-il lorsque l'on clique sur une plante/un specimen ? Doit-on aussi regrouper les spécimens par espèce ?

**Comment by gaetan-pc** [comment]
- [ ] `API ne semble pas retourner les bons résultats`
- [x] `Qu’affiche t-on exactement sur le détail ? 
  - [x] Plant  ? 
  - [x] Description ? 
  - [x] Date d’ajout ?` -> 
- [x] `is_mappable ?` -> disponible

**Comment by loiclouvet** [comment]
>  - [x] `is_mappable ?` -> disponible

@gaetan-pc Disponible mais semble renvoyer `true` sur 1072 (staging) alors que devrait être à false (aucun des spécimens n'est géolocalisé).

**Comment by gaetan-pc** [comment]
> Disponible mais semble renvoyer true sur collection 1072 (staging) alors que devrait être à false (aucun des spécimens n'est géolocalisé).

@loiclouvet semble un couac: specimen avec plante_id == 0 (donc non affiché dans l'appli mobile) mais avec lat/lon. Je n'avais pas pris en compte cette possibilité. Cette situation ne devrait pas exister, je viens d'ajouter des garde-fous pour éviter que ça ne se reproduise.

<img width="250" alt="Capture d’écran 2019-04-16 à 16 18 00" src="https://user-images.githubusercontent.com/3033273/56274888-f089cb00-60ff-11e9-97cf-23b84f848b8a.png">
