### ISSUE TITLE
Gestion des mises à jour de l'application

### ISSUE THREAD

**Issue by gaetan-pc** [floriscope/floriscope-mobile#19]
## Objectifs

* Définition du suivi des versions de l'application
* Forçage du téléchargement des nouvelles versions de l'application si mise à jour majeure

**Comment by loiclouvet** [comment]
Nécessite de pouvoir récupérer le numéro de version minimum pour chacune des plateformes.

Solution simple: rendre accessible un fichier JSON sur un cloud et y placer à minima:
```
{
    "iOS": {
	  "version": {
		  "min": "X.X.X"
	  }
  },
  "android": {
	  "version": {
                   "min": "Y.Y.Y"
	  }
  }
}
```

Sans design préalable, je peux proposer lors du développement un écran se rapprochant des écrans de connexion.

**Comment by loiclouvet** [comment]
Actuellement ne fonctionne pas
