### ISSUE TITLE
Le type du profil utilisateur n'est sauvegardé suite à la création et/ou l'édition du profil 

### ISSUE THREAD

**Issue by gaetan-pc** [floriscope/floriscope-mobile#197]
### Description sommaire

Le type de profil ne semble pas sauvegardé lors de la création ou l'édition du compte.
Vérifier le mapping des variables côté client et côté serveur.

### Screeenshots

![image.png](https://images.zenhubusercontent.com/5a6b0ac14b5806bc2bc46635/aa788acd-faa7-45d4-a8df-167bb19708ff)

**Comment by loiclouvet** [comment]
Mauvais mapping lors de l'affichage du type de profil.
