### ISSUE TITLE
En tant que visiteur, je peux me connecter à mon compte Floriscope

### ISSUE THREAD

**Issue by gaetan-pc** [floriscope/floriscope-mobile#2]
## Comportement(s) attendus

* L'utilisateur entre son email et son mot de passe avec les claviers adaptés
* Le mot de passe est masqué lors de la saisie
* Le bouton de connexion est inactif si les champs email et mots de passe ne sont pas remplis
* Si le format de l'email est mauvais (pas d'arobase, domaine mal formatté) un message d'erreur apparaît
* Lorsque l'utilisateur tape sur le bouton de connexion, un indicateur de chargement type _spinner_ apparaît
* Si la réponse du serveur est OK, transition vers l'écran suivant: _onboarding screen_ / recherche plante
* Si la réponse du serveur est une erreur, afficher le message d'erreur sur la page de connexion

## Ressource(s )API

| Type | Description |
| --- | --- |
| REST Endpoint | <vegebase_api_baseurl>/auth/sign_in |
| Documentation | [https://api.vegebase.io/documentation/auth](https://api.vegebase.io/documentation/ui/index.html?url=/documentation/api/auth/openAPIspecs.json#!/Auth/signin) |

## Maquette(s) écran

| ![login- emailerror](https://user-images.githubusercontent.com/1736502/45697083-3fb94e80-bb65-11e8-85be-8258d33a0226.png) |
|:---:|
|Login Screen|

**Comment by loiclouvet** [comment]
![login- emailerror](https://user-images.githubusercontent.com/1736502/45697083-3fb94e80-bb65-11e8-85be-8258d33a0226.png)
