### ISSUE TITLE
Changer l'intitulé du compteur sur l'écran de consultation des spécimens d'une liste

### ISSUE THREAD

**Issue by gaetan-pc** [floriscope/floriscope-mobile#201]
### Description sommaire

Changer `8 spécimens` par `8 spécimens parmi 5 espèces/variétés` avec:
- spécimens -> `meta.pagination.specimens_count` ou `meta.pagination.hits_count` si recherche active
- espèces/variétés -> `meta.pagination.total_objects`

### Screenshots

![image](https://user-images.githubusercontent.com/3033273/56347706-280e7b00-61c5-11e9-87f3-49041a6fa04b.png)

**Comment by loiclouvet** [comment]
⚠️ Sur la plupart des smartphones, il est fort probable que cet intitulé passent sur 2 lignes.

**Comment by gaetan-pc** [comment]
@loic je soumets ta très bonne suggestion de modification de l'intitulé par ( X espèces - Y spécimens) à l'équipe projet.
Retour prévu pour mercredi
