### ISSUE TITLE
En tant qu'utilisateur, après une création de session (signin/signup) ou à l'ouverture de l'application, je suis dirigé vers un écran d'accueil 

### ISSUE THREAD

**Issue by gaetan-pc** [floriscope/floriscope-mobile#209]
### Description sommaire

Cet écran d'accueil est l'écran par défaut de l'application

### Fonctionnalités attendues

- Si l'utilisateur n'a pas encore consultés la détails d'une plante et/ou d'une collection, la section "Dernières plantes consultées" et/ou "Dernières listes consultées" ne s'affichent pas
- lorsque l'utilisateur clique sur la carte "Image", il est redirigé vers la page de détails de la plante (utilisé les champs `resource_type` et `resource_id`pour les redirections) 

### Screenshots

![image](https://user-images.githubusercontent.com/3033273/58260024-05e4bb80-7d76-11e9-9fdc-a32e25beee8f.png)

### API endpoint

| Type          | Description                          |
| ------------- | ------------------------------------ |
| Récupération des données à afficher sur l'écran d'accueil | [GET] <baseUrl>/v1/home |
| Documentation | voir Paw cloud

### Exemple de réponse

```javascript
{
    "featured_plants": {
        "title": "Plantes à la une...",
        "items": [
            {
                "taxon" : "Quercus robur",
                "vernacular_name": "Chêne pédonculé",
                "image_url": "https://vegebase.imgix.net/pictures/ab03ca00-13fd-45e3-b02e-7c00a7c91ec2.jpg?auto=format&fit=crop&crop=edges&w=800&h=600&gam=27&dpr=1",
                "resource_type": "Plante",
                "resource_id": 127
            }
        ]
    },
    "curated_collections": {
        "title": "Listes thématiques de Plante & Cité",
        "items": [
            {
                "title": "Plantes favorables aux polinisateurs sauvages",
                "image_url": "https://images.unsplash.com/photo-1553242093-eb11b8da8454?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2100&q=80",
                "category": "Liste thématique",
                "resource_type": "Collection",
                "resource_id": 73
            }
        ]

    },
    "last_published_images": {
        "title": "Dernières images publiées",
        "items": [
            {
                "taxon": "Quercus robur",
                "image_url": "https://vegebase.imgix.net/pictures/ab03ca00-13fd-45e3-b02e-7c00a7c91ec2.jpg?auto=format&fit=crop&crop=edges&w=800&h=600&gam=27&dpr=1",
                "copyright": "© Alexis LUMINEAU",
                "resource_type": "Plante",
                "resource_id": 326
            }
        ]
    },
    "last_seen_plants": {
        "tile": "Dernières plantes consultées",
        "items": [
            {
                "taxon" : "Quercus robur",
                "vernacular_name": "Chêne pédonculé",
                "image_url": "https://vegebase.imgix.net/pictures/ab03ca00-13fd-45e3-b02e-7c00a7c91ec2.jpg?auto=format&fit=crop&crop=edges&w=800&h=600&gam=27&dpr=1",
                "resource_type": "Plante",
                "resource_id": 127
            }
        ]
    },
    "last_seen_collections": {
        "title": "Dernières listes consultées",
        "items": [
            {
                "title": "Plantes favorables aux polinisateurs sauvages",
                "image_url": "https://images.unsplash.com/photo-1553242093-eb11b8da8454?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2100&q=80",
                "category": "Liste thématique",
                "resource_type": "Collection",
                "resource_id": 73
            }
        ]
    }
}
```

**Comment by gaetan-pc** [comment]
>### API endpoint
>_en cours de réalisation_

voir les progrès sur https://github.com/gaetan-pc/vegebase-api/issues/163

**Comment by gaetan-pc** [comment]
@loiclouvet correction en cours, voir https://github.com/gaetan-pc/vegebase-api/issues/165

**Comment by loiclouvet** [comment]
> Si l'utilisateur n'a pas encore consultés la détails d'une plante et/ou d'une collection, la section "Dernières plantes consultées" et/ou "Dernières listes consultées" ne s'affichent pas

A faire coté serveur, coté app, on ne peut pas savoir les dernières plantes consultés via le site par ex !

**Comment by gaetan-pc** [comment]
>A faire coté serveur, coté app, on ne peut pas savoir les dernières plantes consultés via le site par ex !

@loiclouvet Fait côté serveur! Si aucune plante et/ou aucune collection consultée, la réponse envoie un array vide pour l'attribut `items` des objets concernées.
