### ISSUE TITLE
Interprétation des codes et messages d'erreurs issues de l'API

### ISSUE THREAD

**Issue by gaetan-pc** [floriscope/floriscope-mobile#21]

**Comment by loiclouvet** [comment]
@gaetan-pc Peux-tu s'il te plait compléter ce ticket ?
Gestion des erreurs en [mode bannière](https://raw.github.com/terryworona/TWMessageBarManager/master/Screenshots/main.png) ?

**Comment by loiclouvet** [comment]
Pour gagner du temps, je suggère que l'on traite ce ticket après avoir implémenter un endpoint API dans l'app.

**Comment by gaetan-pc** [comment]
@loiclouvet en effet, je ne sais pas si ce ticket a vraiment raison d'être. En l'état je comprends que ce soit impossible à chiffrer car cette action sera mise en place dès que tu auras à récupérer des ressources via l'API. Mieux vaut préciser la gestion des erreurs dans chaque user Story comme dans issue #4

**Comment by loiclouvet** [comment]
En phase. Ce ticket a raison d'être uniquement dans le cas d'une gestion transverse des messages d'erreurs (composant transverse aux écrans nécessitant des interactions avec le serveur).
