### ISSUE TITLE
L'utilisateur peut créer une collection en saisissant uniquement son titre 

### ISSUE THREAD

**Issue by gaetan-pc** [floriscope/floriscope-mobile#212]
### Description sommaire

L'utilisateur peut créer une collection en saisissant uniquement son titre.
Une catégorie par défaut est activée dans le formulaire: `Aucune catégorie définie`

**Comment by loiclouvet** [comment]
@gaetan-pc not working server side

**Comment by gaetan-pc** [comment]
@loiclouvet Fixed!
