### ISSUE TITLE
Gérer les différents types d'icônes de l'application en fonction des appareils Apple et Android

### ISSUE THREAD

**Issue by gaetan-pc** [floriscope/floriscope-mobile#223]

**Comment by gaetan-pc** [comment]
@loiclouvet toutes les versions sur dropbox. en espérant que ça passe pour les icônes rondes

![release](https://user-images.githubusercontent.com/3033273/61135773-957b3080-a4c2-11e9-9101-669361158a30.png)

**Comment by loiclouvet** [comment]
@gaetan-pc J'ai mis à jour les icônes actuelles 👌 
En revanche, je ne vois pas les icônes "rondes" que l'on doit aussi ajouter sur Android (voir .zip sur slack).
