### ISSUE TITLE
En tant que membre, lorsque je consulte une plante, je peux afficher des informations supplémentaires

### ISSUE THREAD

**Issue by gaetan-pc** [floriscope/floriscope-mobile#23]
## Comportement(s) attendus

- Lorsqu'un membre consulte le détail d'une plante, il peut afficher les informations descriptives de la dite-plante.
- Les information descriptives sont accessibles dans une tabulation intitulé "Connaître" située dans la partie inférieure de l'écran
- Les descriptives sont regroupés par thème et dans des blocs séparés

## Écran concerné

> PlantScreen - Écran principal de consultation d'une plante

## Navigation

| Ordre     | Type d'écran                         |
| --------- | ------------------------------------ |
| Précédent | /ND|
| Suivant   | /ND |

## Ressource(s )API

|Endpoint      | Params          | Documentation         |
| ---------- | ------------- | --------------------- |
| [GET] {baseUrl}/v1/plantes/{plante_id}/descriptors| *none* | *in progress* (alternative, see Paw Cloud Project)|

## Maquette(s) écran

|  ![img_20181112_114130](https://user-images.githubusercontent.com/3033273/48356872-832cc680-e697-11e8-8295-9b126f49208b.jpg)|
| :-------: |
| Screen Mockup |

**Comment by loiclouvet** [comment]
L'APi décrite ci-dessus renvoie actuellement une `404`

**Comment by gaetan-pc** [comment]
@loiclouvet dans Paw, j'avais inclus des valeurs dynamiques qui pouvait conduire à une erreur 404.
Je modifier l'entrée dans cette documentation provisoire. 
Je vais retravailler le template d'erreur quand la plante est introuvable (ce qui est possible sur le domaine de développement... je dois améliorer les scripts de synchro entre pour la base des plantes en production et sur le domaine de dév car l'index de recherche est basé sur les données en production).
Un ``fetch` sur `https://api.vegebase.net/v1/plantes/127/descriptors' devraient te renvoyer des données. Les thèmes ne sont pas ceux décrits dans les specs mais ça va changer binetôt (dans la semaine).

**Comment by loiclouvet** [comment]
> Les thèmes ne sont pas ceux décrits dans les specs mais ça va changer binetôt (dans la semaine).

Peux-tu me ping quand c'est bon ?

**Comment by gaetan-pc** [comment]
@Loïc Louvet <loic.louvet@gmail.com> migration des données en cours



Le jeu. 29 nov. 2018 à 16:48, Loïc louvet <notifications@github.com> a
écrit :
