### ISSUE TITLE
Bug d'affichage de la liste groupée par espèces des specimens d'une collection

### ISSUE THREAD

**Issue by gaetan-pc** [floriscope/floriscope-mobile#241]
### Description des bugs

- lorsqu'un utilisateur _scroll_ en bas de la liste, une icône de chargement de la suite de la liste apparaît mais quand cette dernière disparaît aucune nouvelle espèce/variété n' a été ajoutée  @loiclouvet 
- les espèces/variétés ne sont pas ordonnées par ordre alphanumérique croissant @gaetan-pc

**Comment by loiclouvet** [comment]
> Du coup :
Coté app, le paramètre page n’etait pas bien envoyé =&gt; corrigé.
En revanche, j’ai d’autres soucis :
- les éléments s’ordonnent par `id` donc si je reçois en page 2 un `id` plus faible qu’un `id` présent page 1, il va se placer avant.. =&gt; *à discuter (fix vs quick win)*
- le nombre ‘nbSpecimens’ ne s’update pas si on fait une recherche textuelle (`specimens_count` pas mis à jour ? utiliser `nb-hits` ?) =&gt; *à discuter*
<sub>[View in Slack](https://floriscope.slack.com/archives/DB07AG4A1/p1565799957000600)</sub>

**Comment by gaetan-pc** [comment]
@loiclouvet la liste récupère bien les specimens de la page suivante.
Pour les autres pb évoqués voir #245 et #246 
Je ferme celle-ci car le fix est OK pour moi
