### ISSUE TITLE
Modifier les règles de publication d'une liste côté client

### ISSUE THREAD

**Issue by gaetan-pc** [floriscope/floriscope-mobile#247]
### Objectif

Une liste peut être rendue publique uniquement si:
  1. sa catégorie n'est pas "Aucune catégorie"
  2. une image a été chargée pour cette liste

**Comment by loiclouvet** [comment]
@gaetan-pc Faut-il afficher un message pour expliquer ? Si oui, coté app/coté serveur ?

**Comment by loiclouvet** [comment]
J'estime uniquement le besoin suivant :
- le switch sera désactivé et grisé dès lors qu'une des conditions n'est pas respectée (pas d'explication pour l'utilisateur)

**Comment by gaetan-pc** [comment]
>@gaetan-pc Faut-il afficher un message pour expliquer ? Si oui, coté app/coté serveur ?

Dans l'idéal, en effet, il faudrait une alerte lorsque l'utilisateur touche le switch désactivé pour rappeler les règles de publication. Peut-être stocké côté app.
