### ISSUE TITLE
En tant que membre, lorsque je consulte une plante, je peux l'ajouter à mes favoris

### ISSUE THREAD

**Issue by gaetan-pc** [floriscope/floriscope-mobile#25]
## Comportement(s) attendus

- Depuis l'écran d'ajout aux listes (voir #26), l'utilisateur connecté peut ajouter/supprimer la plante de ses favoris en cliquant sur un bouton/composant dédié.
- Si la plante est absente des favoris de l'utilisateur, l'action suivante est affichée: **" ➕ Ajouter à mes favoris"**
- Si la plante est présentedes favoris de l'utilisateur, l'action suivante est affichée: **" ✖️ Supprimer de mes favoris"**

## Écran concerné

> AddPlantToListScreen - Écran d'ajout d'une plante aux listes utilisateurs

## Navigation

| Ordre     | Type d'écran                         |
| --------- | ------------------------------------ |
| Précédent | /ND|
| Suivant   | /ND |

## Ressources API

|Endpoint      | Params          | Notes         |
| ---------- | ------------- | --------------------- |
| [GET] {baseUrl}/v1/plantes/{plante_id}| *none* | lorsque le header `Authorization` est ajouté à cette requête, la valeur `isBoorkmarked' est présente dans la réponse. Cette valeur indique la présence/absence de la dite plante dans les favoris de l'utilisateur. |
| [POST] {baseUrl}/v1/plantes/{plante_id}/bookmark| *none* | Ajoute la plante aux favoris |
| [POST] {baseUrl}/v1/plantes/{plante_id}/unbookmark| *none* | Supprime la plante des favoris  |

## Maquette(s) écran

| ![img_20181112_125432](https://user-images.githubusercontent.com/3033273/48471037-48d83c00-e7f3-11e8-90a2-7eb15485c521.jpg)|
| :-------: |
| Screen Mockup |

**Comment by loiclouvet** [comment]
@gaetan-pc Je ne retrouve pas la valeur `isBoorkmarked`, en revanche, je vois dans la réponse l'attribut: `"bookmarks_count": 1`. Peux-tu me dire si c'est normal ?

**Comment by loiclouvet** [comment]
Il y a une coquille dans `isBoorkmarked`=> `isBookmarked`

**Comment by loiclouvet** [comment]
Après utilisation des endpoints pour ajouter une plante aux favoris,e je reçois bien le `isBookmarked`!

**Comment by gaetan-pc** [comment]
@loiclouvet désolé encore un problème de paramètres pour cet _endpoint_ 😊 
Il faut passer le header `Authorization` avec un token valide pour que ce paramètre apparaissent dans la réponse... j'avais oublié de l'ajouter dans la documentation provisoire.
