### ISSUE TITLE
Depuis l'écran de détail des Plantes, ajouter un lien de consultation vers le site Vegestock

### ISSUE THREAD

**Issue by gaetan-pc** [floriscope/floriscope-mobile#254]
## Description

  - Ajout d'un lien de consultation des stocks disponibles sur le site vegestock. 
  - Ouvre une WebView
  - Utiliser l'attribut `vegestock_url` => Done @loiclouvet 

## Capture d'écran

![plantScreen-v1_addStock.png](https://images.zenhubusercontent.com/5a6b0ac14b5806bc2bc46635/43cf660a-c42b-4058-a476-c7e191e5917f)

**Comment by loiclouvet** [comment]
@gaetan-pc  Suite à #249, j'affiche en dessous des boutons ?

**Comment by gaetan-pc** [comment]
@loiclouvet les modifications de l'API pour cette issue sont en production

**Comment by gaetan-pc** [comment]
@loiclouvet j'obtiens cette WebView sur IOS
![image](https://user-images.githubusercontent.com/3033273/66005019-85b02e80-e4aa-11e9-81e4-0f4be968490d.png)

**Comment by loiclouvet** [comment]
Oups, j'ai laissé en dur :
```
 <WebView
    source={{ uri: 'http://aide.floriscope.io' }}
    startInLoadingState
 />
```
Ça sera corrigé pour la prochaine version !
