### ISSUE TITLE
Sur l'écran de détail d'une collection, améliorer le rendu de la description

### ISSUE THREAD

**Issue by gaetan-pc** [floriscope/floriscope-mobile#255]
### Option de résolutions du bug:

  - Côté serveur : rien retirer les balises HTML de l'attribut `description` @gaetan-pc 
  - Côté client mobile: tenter rendre le texte HTML du nouvel attribut `description_html`
à l'aide d'une librairie. Ex: https://github.com/archriss/react-native-render-html @loiclouvet 

### Notes 
Fix temporaire! La mise en place d'un texte riche dans un format structuré de type JSON est inclus dans la ROADMAP des évolutions de l'API

### Captures d'écran

![IMG_A39BAA79F243-1.jpeg](https://images.zenhubusercontent.com/5a6b0ac14b5806bc2bc46635/2d2d4363-77b6-439d-b64b-521c009b2800)

**Comment by loiclouvet** [comment]
Trying [react-native-htmlview](https://github.com/jsdf/react-native-htmlview) first (more ⭐️ and commits are more recents)

**Comment by loiclouvet** [comment]
[react-native-htmlview](https://github.com/jsdf/react-native-htmlview): Supporte le tag `<table>` mais le rendu est moyen :(
[react-native-render-html](https://github.com/archriss/react-native-render-html) Ne supporte pas du tout le tag `<table>` (non affiché)

**Comment by loiclouvet** [comment]
@gaetan-pc Le tag `<table>` n'étant pas bien supporté, j'ai fait le choix de react-native-render-html dans un premier temps

**Comment by gaetan-pc** [comment]
@loiclouvet Bien que le tag `<table>` ne soit pas pris en charge par **react-native-render-html**, la communauté semble avoir rivaliser d'ingéniosité pour compenser ce manque: https://github.com/archriss/react-native-render-html/issues/43
