### ISSUE TITLE
En tant que membre, lorsque je consulte une plante, je peux l'ajouter à une ou plusieurs de mes collections de plantes

### ISSUE THREAD

**Issue by gaetan-pc** [floriscope/floriscope-mobile#26]
## Comportement attendu

- Depuis l'écran de détail d'une plante, lorsqu'un membre clique sur le boutton ➕ présent dans la *headerbar*, un nouvel écran d'ajout aux listes utilisateur apparaît:
  - le titre de ce nouvel écran est **Ajouter cette plante à vos liste** 
  - un bouton `Créer une liste` est afficher
  - en amont de l'affichage des listes utilisateur, une entrée `Ajouter/Supprimer de mes favoris` est affichée - voir #25 
  - les listes utilisateur classée par ordre alphabétique croissant du titre sont affichée ensuite.
- Pour chaque liste utilisateur présente:
  -  l'image, le titre, la catégorie et le nombre de plantes associée sont affichées
- Lorsque l'utilisateur sélectionne une liste: 
  - si la plante est déjà présente dans la liste, une pop-up de confirmation est affiché: **"{plante.taxon} est déjà présente dans cette liste. Voulez-vous quand même l'ajouter? OUI / NON"**
  - si la plante est absente de la liste, un message d'information **" ✔️ Ajoutée à la liste"** est affiché
  - si l'opération n'a pas pu être réalisée (pas de réseau...), un message d'erreur apparaît **" 🚫{plante.taxon} n'a pas pu être ajoutée à votre liste. Veuillez vérifier votre connexion au réseau et réessayer ultérieurement"**
- Lorsque le processus d'ajout est terminé (échec ou succès), l'utilisateur est redirigé vers la page de détail de la plante.

## Écrans concernés

> PlantScreen - Écran principal de consultation d'une plante

>AddPlantToListScreen - Écran secondaire d'ajout aux listes utilisateurs

## Navigation

| Ordre     | Type d'écran                         |
| --------- | ------------------------------------ |
| Précédent | /ND|
| Suivant   | /ND |

## Ressource(s )API

|Endpoint      | Params          | Documentation         |
| ---------- | ------------- | --------------------- |
| [GET] {baseUrl}/v1/collections| `page`, `per_page` | *in progress* (alternative, see Paw Cloud Project)|
> Permet de récupérer toutes les listes de l'utilisateur.

|Endpoint      | Params          | Documentation         |
| ---------- | ------------- | --------------------- |
| [GET] {baseUrl}/v1/collections| `plante_id` | *in progress* (alternative, see Paw Cloud Project)|
> Permet de récupérer listes utilisateurs associé à une plante donnée. Permet de connaître la présence/absence de la plante consultée à une liste. Ce sous-ensemble peut-être utilisé pour gérer côté client l'affichage de la pop-up de confirmation d'ajout

## Maquette(s) écran

| ![img_20181112_125432](https://user-images.githubusercontent.com/3033273/48471037-48d83c00-e7f3-11e8-90a2-7eb15485c521.jpg)|
| :-------: |
| Screen Mockup |

**Comment by loiclouvet** [comment]
> les listes utilisateur classée par ordre alphabétique croissant du titre sont affichée ensuite

Il s'agit du liste paginé, je ne peux donc pas trier coté client (sinon des éléments pourraient apparaitre plus haut lors du scroll bas).
Comment indiquer au serveur que je souhaite les résultats par ordre alphabétique ? @gaetan-pc

**Comment by gaetan-pc** [comment]
>Comment indiquer au serveur que je souhaite les résultats par ordre alphabétique ? @gaetan-pc
@loiclouvet pour l'ordre d'affichage des listes, j'ai ajouté un paramètre `sort` pour le classement.
En gros: 

- `?sort=title`=> classement par ordre croissant du titre 
- `?sort=-title` => classement par ordre décroissant du titre
- par défaut les listes sont **classées par ordre croissant du titre**
- possible de classer selon le titre, la catégorie `category`, la date de création `created_at`, la date de mise à jour `updated_at` et d'autres champs inutiles... (j'ai un peu de refactoring à prévoir mais ça devrait fonctionner, disponible sur le domaine de développement).

**Comment by gaetan-pc** [comment]
>@gaetan-pc Peux-tu me communiquer les infos concernant l'api d'ajout d'une plante à une liste, il semblerait que sur Paw Add a specimen to a given collection ne soit pas à jour où alors j'ai manqué quelque chose 🤔

Théoriquement, il faut passer le plant_id dans le _body_ de cette requête POST. C'est pas terrible, j'essaie de te proposer une _endpoint_ révisée et plus modulaire qui te permettra côté client d'ajouté une plante dans une liste depuis la fenêtre modale mais aussi depuis la page d'édition d'un liste...

@loiclouvet je travaille dessus dans la journée. Je reviens vers toi dans l'après-midi.

**Comment by gaetan-pc** [comment]
>@gaetan-pc Peux-tu me communiquer les infos concernant l'api d'ajout d'une plante à une liste, il semblerait que sur Paw Add a specimen to a given collection ne soit pas à jour où alors j'ai manqué quelque chose 🤔

Théoriquement, il faut passer le plant_id dans le _body_ de cette requête POST. C'est pas terrible, j'essaie de te proposer une _endpoint_ révisée et plus modulaire qui te permettra côté client d'ajouté une plante dans une liste depuis la fenêtre modale mais aussi depuis la page d'édition d'un liste...

@loiclouvet je travaille dessus dans la journée. Je reviens vers toi dans l'après-midi.

**Comment by gaetan-pc** [comment]
>@gaetan-pc Peux-tu me communiquer les infos concernant l'api d'ajout d'une plante à une liste, il semblerait que sur Paw Add a specimen to a given collection ne soit pas à jour où alors j'ai manqué quelque chose 🤔

@loiclouvet Désolé pour le délai de ma réponse. Après réflexion et à ce stage, je ne pense pas que ce soit nécessaire de trop complexifier l'endpoint `POST {base_url}/v1/collections/:collection_id/specimens`. Pour l'instant, il suffit de passer dans le _body_ un object de type:
```javascript
{specimen: {plante_id: 127}}
```
Ce sera peut-être nécessaire de modifier le schéma de réponse si l'association a bien été créée. Pour l'instant le format est le suivant:
```javascript
{
  "data": {
    "id": 119796,
    "taxon": "Magnolia x soulangeana",
    "collection": "Catalogue vente Particuliers",
    "latitude": null,
    "longitude": null
  },
  "response": {
    "code": 201
  },
  "links": {
    "self": "https://api.vegebase.net/v1/collections/95baaf0e-35a1-4369-ab9c-f941853a1a2a/specimens.119796"
  }
}
```
