### ISSUE TITLE
En tant que membre, lorsque je consulte le détail d'une plante, je peux afficher les catégories de collections associées à cette plante  

### ISSUE THREAD

**Issue by gaetan-pc** [floriscope/floriscope-mobile#27]
## Comportement(s) attendus

- Lorsqu'un membre consulte le détail d'une plante, il peut afficher les listes associées de la dite-plante.
- Les catégories de collections sont accessibles dans une tabulation (onglet) intitulé "Découvrir" située dans la partie inférieure de l'écran
- Dans cet  onglet, une liste de catégories de collection incluant un compteur de collections pour chacune des catégories disponible est affiché.
- Chaque entrée de cette liste renvoie vers un écran listant l'ensemble des collections de cette catégorie (voir #101)

## Écran concerné

> PlantScreen - Écran principal de consultation d'une plante

## Navigation

| Ordre     | Type d'écran                         |
| --------- | ------------------------------------ |
| Précédent | /ND|
| Suivant   | /ND |

## Ressource(s )API

|Endpoint      | Response Value          | Notes         |
| ---------- | ------------- | --------------------- |
| [GET] {baseUrl}/v1/plantes/{plante_id}| `collection_count_by_category` | Utiliser cet objet pour générer la liste décrite plus haut|

## Maquette(s) écran

| ![img_20181112_121652](https://user-images.githubusercontent.com/3033273/48444454-47c3f200-e794-11e8-91a3-f255066d9d95.jpg)|
| :-------: |
| Screen Mockup |

**Comment by loiclouvet** [comment]
@gaetan-pc Est-ce implémenté ? Sur Paw, je ne vois pas d'attribut `collection_count_by_category`sur la plante

**Comment by gaetan-pc** [comment]
@loiclouvet non pas encore... je suis dessus. RDV dans 30 minutes 😅

**Comment by gaetan-pc** [comment]
@loiclouvet les modifications ont été deployées sur le domaine de développement. l'attribut `collection_count_by_category` est disponible tout comme la possibilité de classer et filtrer par catégorie les collections (soit celles associées à une plante soit les collections créées par l'utilisateur connecté).
