### ISSUE TITLE
En tant que visiteur, je peux créer un compte Floriscope

### ISSUE THREAD

**Issue by gaetan-pc** [floriscope/floriscope-mobile#4]
## Comportement(s) attendus

* Dans un premier écran, l'utilisateur entre son email, son mot de passe et sa confirmation de mot de passe avec les claviers adaptés
* Dans un second écran, l'utilisateur saisie un identifiant. 
   **Règle (uniquement caractère alphanumérique ou \-_\, min 8 caractères)**
* Dans un second écran, l'utilisateur saisie sa catégorie de profil.
   **Liste des profils**: `["Collectivités territoriales","Entreprises horticoles","Paysagistes concepteurs","Entreprises du paysage","Enseignants", "Étudiants", "Autres"]`

* Les informations demandées dans ces 2 écrans sont requises pour la création du compte utilisateur.
* Le mot de passe et la confirmation de mot de passe sont masqués lors de la saisie
* Les boutons "Suivant" et "Connexion" sont inactifs si tous les champs ne sont pas remplis
* Le bouton "Connexion" reste inactif si le bouton type *switch* d'acception des CGU n'est pas activé (true)
* En tapant sur le lien "Conditions Générales d'Utilisation" ouvre un lien web vers les CGU de Floriscope
   **Lien vers les CGU: _https://s3-eu-west-1.amazonaws.com/vegebase/legals/floriscope_cgu_20170330.pdf_**
* Si le contenu des champs *email* et *identifiant* ne sont pas formattés correctement, un message d'erreur apparaît
* Lorsque l'utilisateur tape sur le bouton de connexion, un indicateur de chargement type _spinner_ apparaît
* Si la réponse du serveur est OK, transition vers l'écran suivant: _onboarding screen_ / recherche plante
* Si la réponse du serveur est une erreur, afficher le message d'erreur sur la page de connexion

### Pour la création du compte (Ecran 1)

| Type | Description |
| --- | --- |
| REST Endpoint | POST <vegebase_api_baseurl>/auth/sign_up |
| Documentation | https://api.vegebase.io/documentation/auth |

### Pour la complétion des données utilisateur (Ecran 2)
| Type | Description |
| --- | --- |
| REST Endpoint | PUT <vegebase_api_baseurl>/v1/users/me |
| Documentation | [https://api.vegebase.io/documentation/v1/users/me](https://api.vegebase.io/documentation/ui/index.html?url=/documentation/api/v1/openAPIspecs.json#!/Utilisateur/put_users_me) |

### Écrans principaux

| ![Signup #1.png](https://images.zenhubusercontent.com/5a6b0ac14b5806bc2bc46635/109e421e-284d-45dd-ad1f-bfd3a2dfd923)| ![Signup #2.png](https://images.zenhubusercontent.com/5a6b0ac14b5806bc2bc46635/af02bf3e-aa64-4d14-8851-c7e373a7b816)|
|:---:|:---:|
| Signup | Update Account |

### Écrans d'erreur Création de compte

|![Signup #1 ErrorEmail.png](https://images.zenhubusercontent.com/5a6b0ac14b5806bc2bc46635/e77c2083-4c73-4392-8591-1f921ae91990) |![Signup #1 ErrorPassword.png](https://images.zenhubusercontent.com/5a6b0ac14b5806bc2bc46635/9bb55dea-7768-4766-abcc-e0b98015d394) | ![Signup #1 ErrorPasswordConfirmation.png](https://images.zenhubusercontent.com/5a6b0ac14b5806bc2bc46635/c055e083-efea-44ef-839c-bc67b2e46367)|
|:---:|:---:|:---:|
| emailError| passwordError  | passwordConfirmationError |

### Écrans d'erreur Mise à jour du profil Utilisateur

|![Signup #2 - Error.png](https://images.zenhubusercontent.com/5a6b0ac14b5806bc2bc46635/6b447ff4-fd58-4fa1-ada5-09b9e3df1d21) |
|:---:|
| usernameFormatError |

**Comment by loiclouvet** [comment]
> Si la réponse du serveur est une erreur, afficher le message d'erreur sur la page de connexion

Bannière temporaire affichant l'erreur ? Affichage de l'erreur entre le logo et le 1er champs ?
Attention, il est possible que l'adresse renseignée dans le premier écran soit déjà utilisée pour un autre compte. Selon la description, un message d'erreur sera affiché sur le 2nd écran uniquement. Faut-il prévoir un retour automatique ?

_Suggestion:
Enlever le switch et remplacer le texte par "En m'inscrivant, j'accepte les Conditions Générales d'Utilisation"._

**Comment by gaetan-pc** [comment]
>Bannière temporaire affichant l'erreur ? Affichage de l'erreur entre le logo et le 1er champs ?

Oui, ça me paraît bien. L'UX n'étant pas mon fort, souvent je m'inspire des [guidelines proposées par Shopify](https://polaris.shopify.com/patterns/error-messages#navigation) 

>Attention, il est possible que l'adresse renseignée dans le premier écran soit déjà utilisée pour un autre compte. Selon la description, un message d'erreur sera affiché sur le 2nd écran uniquement. Faut-il prévoir un retour automatique ?

Merci pour cette remarque ! Ce n'est pas idéal d'avoir une validation au second écran et de devoir revenir au premier écran si erreur. Je te fais une contre proposition pour les écrans avec une proposition de pour la bannière d'erreur

> Suggestion:
Enlever le switch et remplacer le texte par "En m'inscrivant, j'accepte les Conditions Générales d'Utilisation".

Je crois que légalement, l'utilisateur doit engager une interaction pour marquer son consentement (checkbox ou switch). En tout cas, c'est ce que nous avait dit le cabinet qui nous avait accompagné dans la rédaction des CGU.

**Comment by loiclouvet** [comment]
> Merci pour cette remarque ! Ce n'est pas idéal d'avoir une validation au second écran et de devoir revenir au premier écran si erreur. Je te fais une contre proposition pour les écrans avec une proposition de pour la bannière d'erreur

Qu'en est-il ?

**Comment by loiclouvet** [comment]
@gaetan-pc Concernant les messages d'erreurs (mot de passe => 8 char, nom d'utilisateur => char interdits). Sont-ils des messages renvoyés par le serveur ou doivent-ils être gérés coté client (App) ?

**Comment by gaetan-pc** [comment]
@loiclouvet les messages d'erreurs pour `password` et `username` sont gérés côté serveur. 

Ce qui n'est pas géré côté serveur, c'est la catégorie d'utilisateur. Elle est requise pour la validation du compte _côté client_, mais je n'ai créé aucune validation _côté serveur_ pour plusieurs raisons.
À mon avis, le comportement _côté client_ pourrait être le suivant:

1. sur le second écran, les champs `username` et `category` sont requis
2. un message d'erreur peut apparaître si l'input a été sélectionné mais non rempli (pour info, un nom d'utilisateur par défaut est fourni suite au *sign_up*)
3. le bouton "Activer mon compte" devient actif (l'utilisateur peut toucher le bouton pour envoyer la requête) si ces 2 champs sont bien remplis.

Qu'en penses-tu?
