### ISSUE TITLE
En tant que membre, lorsque je consulte l'écran de connexion, je dois pouvoir réinitialiser mon mot de passe oublié

### ISSUE THREAD

**Issue by gaetan-pc** [floriscope/floriscope-mobile#57]
## Comportement(s) attendus

* Après avoir saisi et validé son email, l'utilisateur recevra un courriel de réinitialisation de son mot de passe
* Si l'adresse électronique existe en base, un message d'information concernant l'envoi en cours de ce courriel apparaît, ce message contient un lien pour ouvrir l'application de messagerie par défaut sur l'appareil. Puis redirection automatique vers la page de connexion
* Si l'adresse électronique n'existe pas en base un message d'alerte apparaît => redirection possible vers la page de création de compte

## Ressource(s )API

| Type | Description |
| --- | --- |
| REST Endpoint | POST <vegebase_api_baseurl>/auth/reset_password |
| Documentation | [Demander la réinitialisation de son mot de passe](https://api.vegebase.io/documentation/ui/index.html?url=/documentation/api/auth/openAPIspecs.json#!/Settings/reset_password) |

## Maquette(s) écran

|![Reset Password.png](https://images.zenhubusercontent.com/5a6b0ac14b5806bc2bc46635/98438953-47c0-4b5d-b79b-208c99523ce2) |![Reset Password Confirmation Message.png](https://images.zenhubusercontent.com/5a6b0ac14b5806bc2bc46635/8e9c50e6-7c74-48b7-83e9-e053f18ed804) |![Reset Password Error.png](https://images.zenhubusercontent.com/5a6b0ac14b5806bc2bc46635/4901d300-b787-4293-be93-12cde88a03c4)|
|:---:|:---:|:---:|
| Ecran de réinitialisation| Message de confirmation | Message d'erreur |

**Comment by loiclouvet** [comment]
@gaetan-pc Je vais ajouter un bouton `retour` sur cet écran qui permettra de revenir sur l'écran de login. Ainsi, si depuis l'écran de login, on clique sur "Créer un compte" sans le vouloir, on pourra revenir sur l'écran de login. La redirection automatique vers login après une réinitialisation de mot de passe est toujours d'actualité !
