### ISSUE TITLE
En tant que membre, je peux visualiser mes données de profil

### ISSUE THREAD

**Issue by gaetan-pc** [floriscope/floriscope-mobile#6]
## Comportement(s) attendus

* Lorsqu'un utilisateur (dont la session est active) tape sur le lien adéquat, sa page de profil apparaît
* Depuis sa page de profil, l'utilisateur __peut consulter__:
   * les informations principales de son profil: _avatar, fond d'écran, username, email, organisation..._
   * ses plantes favorites
   * ses collections de plantes favorites
   * les collections de plantes dont il est le propriétaire
* Depuis sa page de profil, l'__utilisateur peut__:
   * ~~accéder à un écran de modification de ses informations et de configuration de ses paramètres~~
   * déconnecter son compte de l'application

## Navigation

| Ordre     | Type d'écran                         |
| --------- | ------------------------------------ |
| Précédent | /ND. Navigation par _tab_ |
| Suivant   | _ND_ . Navigation par _tab_    |

### Récupération des données de l'utilisateur
| Type          | Description                          |
| ------------- | ------------------------------------ |
| REST Endpoint | GET <ressource_api_baseurl>/v1/users/me |
| Documentation | [Récupération des informations de profil de l'utilisateur](https://api.vegebase.io/documentation/ui/index.html?url=/documentation/api/v1/openAPIspecs.json#!/Utilisateur/get_users_me)  

### Récupération des listes de l'utilisateur
| Type          | Description                          |
| ------------- | ------------------------------------ |
| REST Endpoint | GET <ressource_api_baseurl>/v1/collections |
| Documentation | [Récupération des listes de l'utilisateur](https://api.vegebase.io/documentation/ui/index.html?url=/documentation/api/v1/openAPIspecs.json#!/Listes/get_collections)                                  |

### Récupération des plantes favorites
| Type          | Description                          |
| ------------- | ------------------------------------ |
| REST Endpoint | GET <ressource_api_baseurl>/v1/bookmarks/plantes |
| Documentation | [Récupérer les plantes favorites](https://api.vegebase.io/documentation/ui/index.html?url=/documentation/api/v1/openAPIspecs.json#!/Favoris/get_bookmarks_plantes)                                 |

### Récupération des listes favorites
| Type          | Description                          |
| ------------- | ------------------------------------ |
| REST Endpoint | GET <ressource_api_baseurl>/v1/bookmarks/listes |
| Documentation | [Récuperer les listes favorites](https://api.vegebase.io/documentation/ui/index.html?url=/documentation/api/v1/openAPIspecs.json#!/Favoris/get_bookmarks_listes) |

### Déconnexion de l'application
| Type          | Description                          |
| ------------- | ------------------------------------ |
| REST Endpoint | PUT <ressource_api_baseurl>/auth/sign_out |
| Documentation | [Récuperer les listes favorites](http://api.vegebase.io/documentation/ui/index.html?url=/documentation/api/auth/openAPIspecs.json#!/Auth/signout) |

## Maquette(s) écran

|![Listes.png](https://images.zenhubusercontent.com/5a6b0ac14b5806bc2bc46635/d89a89e8-a09e-4881-91ec-3134d0fb2a49)|
| :-------: |
| Profil :: Collections de plantes personnelles|

|![Favoris.png](https://images.zenhubusercontent.com/5a6b0ac14b5806bc2bc46635/0309b9a2-8491-4ba3-ba16-f85df962963f)|
| :-------: |
| Profil :: Favoris|

**Comment by loiclouvet** [comment]
@gaetan-pc Peux-tu me confirmer que ce ticket doit traiter uniquement la partie haute de l'écran ? cf #8 et #9.

**Comment by loiclouvet** [comment]
@gaetan-pc Comment gère t-on les messages d'erreur sur cet écran ?
