### ISSUE TITLE
Mise en place des icônes de l'application pour Android et iOS

### ISSUE THREAD

**Issue by loiclouvet** [floriscope/floriscope-mobile#64]
@gaetan-pc Peux-tu m'envoyer les icônes ou une image originale du logo afin que je puisse mettre en place les icônes sur Android et iOS ?

**Comment by gaetan-pc** [comment]
@loiclouvet Je viens de les ajouter sur notre[ espace partagé](https://www.dropbox.com/sh/mkh4f5e9szxaf4c/AAAiMnhlki4UHRR7KkYNzD5Oa?dl=0)

**Comment by loiclouvet** [comment]
@gaetan-pc Il me manque les icônes suivantes sur iOS: 
<img width="671" alt="capture d ecran 2018-09-17 a 10 09 54" src="https://user-images.githubusercontent.com/1736502/45613288-1a91e680-ba66-11e8-9847-17492729c7c6.png">

Sur Android, j'ai bien tous les formats mais le rendu est moyen avec des icônes carrés :
<img width="268" alt="capture d ecran 2018-09-17 a 10 39 44" src="https://user-images.githubusercontent.com/1736502/45613326-3c8b6900-ba66-11e8-8d65-eb6938c92745.png">
