### ISSUE TITLE
Compteurs de facettes de recherche non actualisés si recherche modifiée

### ISSUE THREAD

**Issue by gaetan-pc** [floriscope/floriscope-mobile#96]
**Description**
Le compteur associé aux valeurs des filtres ne s'actualise pas lorsque l'input recherche est  modiffié et/ou lorsque de nouveaux filtres sont activés.

**Version de l'application / Matériel et OS ciblés**
 - Version: 0.2.0
 - Device: iPhone 6s
 - OS: iOS 12.0

**Comportement actuel**
1. Modifier la recherche textuelle avec le terme `Camellia` par exemple
2. Cliquer sur le bouton de filtre de la recherche
4. Sélectionner le filtre **Catégorie**
5. Les compteurs des valeurs de filtres sont identiques à ceux d'une recherche vide.

**Comportement attendu**
1. Modifier la recherche textuelle avec le terme `Camellia` par exemple
2. Cliquer sur le bouton de filtre de la recherche
4. Sélectionner le filtre **Catégorie**
5. Les compteurs des valeurs de filtres devrait correspondre aux nombres de résultats disponibles (1519 plantes pour le terme de recherche `Camellia` à la date du description du problème)

## Captures d'écran

**1. Sur la version web**
![Capture d’écran 2018-11-08 à 11.29.53.png](https://images.zenhubusercontent.com/5a6b0ac14b5806bc2bc46635/27b11089-f02e-436a-a532-a1f49fcc6c5c)
*Compteur des facettes de catégorie pour une recherche vide*

![Capture d’écran 2018-11-08 à 11.30.12.png](https://images.zenhubusercontent.com/5a6b0ac14b5806bc2bc46635/0895e35b-6a75-45dd-b700-d604b341cf4e)
*Compteur de facettes de catégorie pour une recherche sur Camellia*

**2. Version mobile 0.2.0**
![IMG_3329.PNG](https://images.zenhubusercontent.com/5a6b0ac14b5806bc2bc46635/28db4d87-c3b1-4a27-b3c5-637a25f8a447)
*Recherche sur Camellia*

![IMG_3330.PNG](https://images.zenhubusercontent.com/5a6b0ac14b5806bc2bc46635/ef28aa1f-004f-4594-8fd3-6edf64e7680e)
*Compteur de facettes de catégorie pour une recherche sur Camellia*

**Comment by gaetan-pc** [comment]
👍 Parfait!

**Comment by gaetan-pc** [comment]
@loiclouvet je viens de me rendre compte que les compteurs des valeurs de filtres n'étaient pas actualisés suite à la sélection d'une valeur. 
Exemple: sur une recherche vide, je sélectionne la valeur `soleil` pour le filtre **Exposition** et j'obtiens 3419 plantes. Si je sélectionne le filtre **Catégorie**, toutes les valeurs sont affichées et les compteurs ne sont pas actualisés. Par exemple, la valeur *Vivaces* a toujours un compteur 14 105 alors qu'il devrait être de 1 048.

**Comment by loiclouvet** [comment]
@gaetan-pc OK je viens de comprendre et de reproduire facilement, je m'en occupe en priorité !

**Comment by gaetan-pc** [comment]
@loiclouvet c'est ça!
